# Generated by Django 2.2.13 on 2020-07-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
