# Generated by Django 2.2.13 on 2020-07-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200703_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='art',
        ),
    ]
